export default function RootLayout({ children }) {
  return (
    <html>
      <body>{children}</body>
    </html>
  );
}
/**import { Geist, Geist_Mono, Host_Grotesk, Merriweather} from "next/font/google";
import "./globals.css";



const hostGrotesk = Host_Grotesk({
  subsets: ["latin"],
});

const merriweather = Merriweather({
  subsets: ["latin"],
});


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} ${merriweather.variable} ${hostGrotesk.variable}`}>
      <body>{children}</body>
    </html>
  );
}**/
